ALTER TABLE robots ADD COLUMN robot_type VARCHAR(25) NOT NULL DEFAULT 'REAL';
ALTER TABLE robots ADD COLUMN robot_mode VARCHAR(25) NOT NULL DEFAULT 'PRODUCTION';
ALTER TABLE devices ADD COLUMN device_type VARCHAR(25) NOT NULL DEFAULT 'REAL';
ALTER TABLE devices ADD COLUMN device_mode VARCHAR(25) NOT NULL DEFAULT 'PRODUCTION';


UPDATE robots SET robot_type='REAL',robot_mode='PRODUCTION';
UPDATE devices SET device_type='REAL',device_mode='PRODUCTION';
